name: bungie_api
description: This project implements Dart definitions and API helpers for the [Bungie.net API](https://github.com/Bungie-net/api).

version: 13.19.0

homepage:
  https://github.com/LittleLightForDestiny/bungie-api-dart.git

dependencies:
  compute: ^1.0.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9 
  json_serializable: ^6.8.0

environment:
  sdk: ">=3.7.0 <=3.8.1"
