name: bungie_api
description: This project implements Dart definitions and API helpers for the [Bungie.net API](https://github.com/Bungie-net/api).

version: 13.16.1

homepage:
  https://github.com/LittleLightForDestiny/bungie-api-dart.git

dependencies:
  compute: ^1.0.2
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.2 
  json_serializable: ^5.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"