class DestinyItemSubType {
  DestinyItemSubType._();
  static const int none = 0;
  static const int crucible = 1;
  static const int vanguard = 2;
  static const int exotic = 5;
  static const int autoRifle = 6;
  static const int shotgun = 7;
  static const int machinegun = 8;
  static const int handCannon = 9;
  static const int rocketLauncher = 10;
  static const int fusionRifle = 11;
  static const int sniperRifle = 12;
  static const int pulseRifle = 13;
  static const int scoutRifle = 14;
  static const int crm = 16;
  static const int sidearm = 17;
  static const int sword = 18;
  static const int mask = 19;
  static const int shader = 20;
  static const int ornament = 21;
  static const int fusionRifleLine = 22;
  static const int grenadeLauncher = 23;
  static const int submachineGun = 24;
  static const int traceRifle = 25;
  static const int helmetArmor = 26;
  static const int gauntletsArmor = 27;
  static const int chestArmor = 28;
  static const int legArmor = 29;
  static const int classArmor = 30;
  static const int bow = 31;
}