class DestinyItemSubType {
  DestinyItemSubType._();
  static const int None = 0;
  static const int Crucible = 1;
  static const int Vanguard = 2;
  static const int Exotic = 5;
  static const int AutoRifle = 6;
  static const int Shotgun = 7;
  static const int Machinegun = 8;
  static const int HandCannon = 9;
  static const int RocketLauncher = 10;
  static const int FusionRifle = 11;
  static const int SniperRifle = 12;
  static const int PulseRifle = 13;
  static const int ScoutRifle = 14;
  static const int Crm = 16;
  static const int Sidearm = 17;
  static const int Sword = 18;
  static const int Mask = 19;
  static const int Shader = 20;
  static const int Ornament = 21;
  static const int FusionRifleLine = 22;
  static const int GrenadeLauncher = 23;
  static const int SubmachineGun = 24;
  static const int TraceRifle = 25;
  static const int HelmetArmor = 26;
  static const int GauntletsArmor = 27;
  static const int ChestArmor = 28;
  static const int LegArmor = 29;
  static const int ClassArmor = 30;
  static const int Bow = 31;
}
