class DestinyComponentType {
  DestinyComponentType._();
  static const int None = 0;
  static const int Profiles = 100;
  static const int VendorReceipts = 101;
  static const int ProfileInventories = 102;
  static const int ProfileCurrencies = 103;
  static const int ProfileProgression = 104;
  static const int Characters = 200;
  static const int CharacterInventories = 201;
  static const int CharacterProgressions = 202;
  static const int CharacterRenderData = 203;
  static const int CharacterActivities = 204;
  static const int CharacterEquipment = 205;
  static const int ItemInstances = 300;
  static const int ItemObjectives = 301;
  static const int ItemPerks = 302;
  static const int ItemRenderData = 303;
  static const int ItemStats = 304;
  static const int ItemSockets = 305;
  static const int ItemTalentGrids = 306;
  static const int ItemCommonData = 307;
  static const int ItemPlugStates = 308;
  static const int Vendors = 400;
  static const int VendorCategories = 401;
  static const int VendorSales = 402;
  static const int Kiosks = 500;
  static const int CurrencyLookups = 600;
  static const int PresentationNodes = 700;
  static const int Collectibles = 800;
  static const int Records = 900;
}
