class DestinyComponentType {
  DestinyComponentType._();
  static const int none = 0;
  static const int profiles = 100;
  static const int vendorReceipts = 101;
  static const int profileInventories = 102;
  static const int profileCurrencies = 103;
  static const int profileProgression = 104;
  static const int characters = 200;
  static const int characterInventories = 201;
  static const int characterProgressions = 202;
  static const int characterRenderData = 203;
  static const int characterActivities = 204;
  static const int characterEquipment = 205;
  static const int itemInstances = 300;
  static const int itemObjectives = 301;
  static const int itemPerks = 302;
  static const int itemRenderData = 303;
  static const int itemStats = 304;
  static const int itemSockets = 305;
  static const int itemTalentGrids = 306;
  static const int itemCommonData = 307;
  static const int itemPlugStates = 308;
  static const int vendors = 400;
  static const int vendorCategories = 401;
  static const int vendorSales = 402;
  static const int kiosks = 500;
  static const int currencyLookups = 600;
  static const int presentationNodes = 700;
  static const int collectibles = 800;
  static const int records = 900;
}