import 'application_developer.dart';

/**  */
class Application{
	
	/**  */
	int applicationType;
	
	/** Unique ID assigned to the application */
	int applicationId;
	
	/** Name of the application */
	String name;
	
	/** URL used to pass the user's authorization code to the application */
	String redirectUrl;
	
	/** Link to website for the application where a user can learn more about the app. */
	String link;
	
	/** Permissions the application needs to work */
	String scope;
	
	/** Value of the Origin header sent in requests generated by this application. */
	String origin;
	
	/** Current status of the application. */
	int status;
	
	/** Date the application was first added to our database. */
	String creationDate;
	
	/** Date the application status last changed. */
	String statusChanged;
	
	/** Date the first time the application status entered the 'Public' status. */
	String firstPublished;
	
	/** List of team members who manage this application on Bungie.net. Will always consist of at least the application owner. */
	List<ApplicationDeveloper> team;
	Application(
		this.applicationType,
		this.applicationId,
		this.name,
		this.redirectUrl,
		this.link,
		this.scope,
		this.origin,
		this.status,
		this.creationDate,
		this.statusChanged,
		this.firstPublished,
		this.team,
	);

	static Application fromMap(Map<String, dynamic> data){
		if(data == null) {
			return null;
		};
		return new Application(
				data['applicationType'],
				data['applicationId'],
				data['name'],
				data['redirectUrl'],
				data['link'],
				data['scope'],
				data['origin'],
				data['status'],
				data['creationDate'],
				data['statusChanged'],
				data['firstPublished'],
				data['team'] != null ? ApplicationDeveloper.fromList(data['team']) : null,
		);
	}

	static List<Application> fromList(List<dynamic> data){
		if(data == null) {
			return null;
		};
		List<Application> list = new List();
    data.forEach((item) {
      list.add(Application.fromMap(item));
    });
    return list;
	}

	Map<String, dynamic> toMap(){
		Map<String, dynamic> data = new Map();
			data['applicationType'] = this.applicationType;
			data['applicationId'] = this.applicationId;
			data['name'] = this.name;
			data['redirectUrl'] = this.redirectUrl;
			data['link'] = this.link;
			data['scope'] = this.scope;
			data['origin'] = this.origin;
			data['status'] = this.status;
			data['creationDate'] = this.creationDate;
			data['statusChanged'] = this.statusChanged;
			data['firstPublished'] = this.firstPublished;
			data['team'] = this.team.map((item)=>item.toMap()).toList();
		return data;
	}
}