/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bugie-api-ts
 * Do not edit these files manually.
 */

import 'dart:async';
import '../http.dart';

import '../common.dart';
import './interfaces.dart';

abstract class GetApplicationApiUsageParams {
  /** ID of the application to get usage statistics. */
  int applicationId;
  /** End time for query. Goes to now if not specified. */
  String end;
  /** Start time for query. Goes to 24 hours ago if not specified. */
  String start;
}

/**
 * Get API usage by application for time frame specified. You can go as far back as
 * 30 days ago, and can ask for up to a 48 hour window of time in a single request.
 * You must be authenticated with at least the ReadUserData permission to access
 * this endpoint.
 */
  Future<ServerResponse<ApiUsage>> getApplicationApiUsage(HttpClient http, GetApplicationApiUsageParams params) {
  return http.request(new HttpClientConfig(
    'GET',
    "https://www.bungie.net/Platform/App/ApiUsage/${params.applicationId}/",
    {
      'end': params.end,
      'start': params.start
    },
    null
    ));
}

/** Get list of applications created by Bungie. */
  Future<ServerResponse<List<Application>>> getBungieApplications(HttpClient http) {
  return http.request(new HttpClientConfig(
    'GET',
    "https://www.bungie.net/Platform/App/FirstParty/",
    null,
    null
    ));
}
