/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bugie-api-ts
 * Do not edit these files manually.
 */

import '../common.dart';
import '../user/interfaces.dart';

class ApiUsage {
  /** The date range for the data being reported. */
  int range;
  /** Counts for on API calls made for the time range. */
  List<Series> apiCalls;
  /**
   * Instances of blocked requests or requests that crossed the warn threshold during
   * the time range.
   */
  List<Series> throttledRequests;
}

class Series {
  /** Collection of samples with time and value. */
  List<Datapoint> datapoints;
  /** Target to which to datapoints apply. */
  String target;
}

class Datapoint {
  /** Timestamp for the related count. */
  String time;
  /** Count associated with timestamp */
  double count;
}

class Application {
  OAuthApplicationType applicationType;
  /** Unique ID assigned to the application */
  int applicationId;
  /** Name of the application */
  String name;
  /** URL used to pass the user's authorization code to the application */
  String redirectUrl;
  /** Link to website for the application where a user can learn more about the app. */
  String link;
  /** Permissions the application needs to work */
  String scope;
  /** Value of the Origin header sent in requests generated by this application. */
  String origin;
  /** Current status of the application. */
  int status;
  /** Date the application was first added to our database. */
  String creationDate;
  /** Date the application status last changed. */
  String statusChanged;
  /** Date the first time the application status entered the 'Public' status. */
  String firstPublished;
  /**
   * List of team members who manage this application on Bungie.net. Will always
   * consist of at least the application owner.
   */
  List<ApplicationDeveloper> team;
}

class OAuthApplicationType {
   static const int None = 0;
  /**
   * Indicates the application is server based and can keep its secrets from end
   * users and other potential snoops.
   */
   static const int Confidential = 1;
  /**
   * Indicates the application runs in a public place, and it can't be trusted to
   * keep a secret.
   */
   static const int Public = 2;
}

class ApplicationStatus {
  /** No value assigned */
   static const int None = 0;
  /**
   * Application exists and works but will not appear in any public catalog. New
   * applications start in this state, test applications will remain in this state.
   */
   static const int Private = 1;
  /** Active applications that can appear in an catalog. */
   static const int Public = 2;
  /**
   * Application disabled by the owner. All authorizations will be treated as
   * terminated while in this state. Owner can move back to private or public state.
   */
   static const int Disabled = 3;
  /**
   * Application has been blocked by Bungie. It cannot be transitioned out of this
   * state by the owner. Authorizations are terminated when an application is in this
   * state.
   */
   static const int Blocked = 4;
}

class ApplicationDeveloper {
  DeveloperRole role;
  int apiEulaVersion;
  UserInfoCard user;
}

class DeveloperRole {
   static const int None = 0;
   static const int Owner = 1;
   static const int TeamMember = 2;
}
