/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bugie-api-ts
 * Do not edit these files manually.
 */

class IgnoreResponse {
  bool isIgnored;
  IgnoreStatus ignoreFlags;
}

class IgnoreStatus {
   static const int NotIgnored = 0;
   static const int IgnoredUser = 1;
   static const int IgnoredGroup = 2;
   static const int IgnoredByGroup = 4;
   static const int IgnoredPost = 8;
   static const int IgnoredTag = 16;
   static const int IgnoredGlobal = 32;
}

class PartnershipType {
   static const int None = 0;
   static const int Twitch = 1;
}

class TagResponse {
  String tagText;
  IgnoreResponse ignoreStatus;
}
