/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.2
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-dart code generator program.
 * https://github.com/marquesinijatinha/bungie-api-dart
 * Do not edit these files manually.
 */

import 'dart:async';
import '../http.dart';

import '../common.dart';
import './interfaces.dart';

/**
 * Returns trending items for Bungie.net, collapsed into the first page of items
 * per category. For pagination within a category, call GetTrendingCategory.
 */
  Future<ServerResponse<TrendingCategories>> getTrendingCategories(HttpClient http) {
  return http.request(new HttpClientConfig(
    'GET',
    "https://www.bungie.net/Platform/Trending/Categories/",
    null,
    null
    ));
}

abstract class GetTrendingCategoryParams {
  /** The ID of the category for whom you want additional results. */
  String categoryId;
  /** The page # of results to return. */
  int pageNumber;
}

/** Returns paginated lists of trending items for a category. */
  Future<ServerResponse<SearchResultOfTrendingEntry>> getTrendingCategory(HttpClient http, GetTrendingCategoryParams params) {
  return http.request(new HttpClientConfig(
    'GET',
    "https://www.bungie.net/Platform/Trending/Categories/${params.categoryId}/${params.pageNumber}/",
    null,
    null
    ));
}

abstract class GetTrendingEntryDetailParams {
  /** The identifier for the entity to be returned. */
  String identifier;
  /** The type of entity to be returned. */
  TrendingEntryType trendingEntryType;
}

/**
 * Returns the detailed results for a specific trending entry. Note that trending
 * entries are uniquely identified by a combination of *both* the TrendingEntryType
 * *and* the identifier: the identifier alone is not guaranteed to be globally
 * unique.
 */
  Future<ServerResponse<TrendingDetail>> getTrendingEntryDetail(HttpClient http, GetTrendingEntryDetailParams params) {
  return http.request(new HttpClientConfig(
    'GET',
    "https://www.bungie.net/Platform/Trending/Details/${params.trendingEntryType}/${params.identifier}/",
    null,
    null
    ));
}
